all:
  vars:
    ansible_connection: lxd
    ansible_user: root
    ansible_become: false
  children:
    local:
      vars:
        ansible_lxd_remote: local
        ansible_lxd_project: default
      hosts:
        v1:
        c1:
  